// <auto-generated />
namespace FinanceTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddExpanseFlag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddExpanseFlag));
        
        string IMigrationMetadata.Id
        {
            get { return "202301010917352_AddExpanseFlag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
